[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pdf-epub-converter"
version = "0.1.0"
description = "Conversion PDF/EPUB to Markdown for RAG"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4",
    "ebooklib",
    "google-genai",
    "markdownify",
    "pdfplumber",
    "pymupdf4llm",
    "pyyaml",
    "requests",
    "customtkinter",
    "CTKMessagebox",
    "python-dotenv"
]
[project.scripts]
convert = "main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
