name: CI with uv

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1.Installing uv
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true # Enable caching so that dependencies aren't downloaded from scratch every time.

      # 2. Installing Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      # 3. Synchronizing dependencies and running tests
      - name: Install dependencies and run tests
        run: |
          uv sync --group dev
          uv run pytest --cov=. --cov-branch --cov-report=term-missing